


seed = 42


claim_count = 1000


anomaly_rate = 0.01  





output_format = "json"


[anomaly_rates]
missing_field = 0.3
invalid_value = 0.2
invalid_date_format = 0.1
duplicate_claim = 0.05
invalid_procedure_code = 0.15
invalid_modifier_combination = 0.1
age_gender_mismatch = 0.05
invalid_provider = 0.1
invalid_patient_info = 0.2
missing_documentation = 0.1
